// functions/_lib/dedupe.js
// The scan_findings dedupe key. Shared by the weekly scan and the admin
// manual-add path so a hand-added story and a scan-found one collide correctly
// (i.e. adding a story by hand stops the scan from re-adding it later).
//
// Deliberately DERIVED IN CODE from the article URL rather than generated by the
// LLM: an LLM-written slug is non-deterministic ("hearing" vs "hearings" on
// consecutive runs), which silently broke cross-run dedup until July 2026.

/** Normalized article URL: host+path, lowercased, no query string or trailing slash. */
export function normalizeUrl(u) {
  if (!u) return "";
  try {
    const url = new URL(u);
    return `${url.host}${url.pathname}`.toLowerCase().replace(/\/+$/, "");
  } catch {
    return u.split("?")[0].replace(/\/+$/, "").toLowerCase();
  }
}

/** Fallback key when an item has no URL at all. */
export function titleKey(t) {
  return (t || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

/** The key stored on a finding. */
export function dedupeKeyFor({ source_url, title }) {
  return normalizeUrl(source_url) || titleKey(title);
}
